In [ ]:
print("Hello List")

In [ ]:
x = [23,54,74,True,"Ruby",False,'Python',0,1,None,23]
print(x)
print(len(x))

In [ ]:
print(x[0])
print(x[5])
print(x[8])
print(x[-2])
print(x[-5])
print(x[-11])
print(x[-12])

In [ ]:
x = [23,54,74,True,"Ruby",False,'Python',0,1,None,23]
print(x)
print(x[2])
print(x[7])
print(x[2:7])
print(x[4:1:2])
print(x[4:1:-1])

In [ ]:
x = [23,54,74,True,["Ruby",False,'Python'],0,1,None,23]
print(x)
print(x[3])
print(x[-3])
print(x[4])
#print(x[4,0])
print(x[4][-2])
print(x[4][-3])
#print(x[4][-4])
print(x[4][1:])
print(x[4][:2])
print(x[4][1:2])

In [ ]:
x = [23,54,74,True,["Ruby",False,'Python'],[0,1,None,[23]]]
print(x)
new_list = []
for i in x:
    if isinstance(i,list):
        new_list.extend(i)
    else:
        new_list.append(i)
print(new_list)

In [ ]:
u = ['naman','vinay']
u.append('David')
print(u)

In [ ]:
u.append('Backham')

In [ ]:
u.append(['Backham'])

In [ ]:
u

In [ ]:
u.extend("Rajni")
u

In [ ]:
u.extend(["Rajni"])
u

In [ ]:
i = ['Ayushi','ayush']
j = ['Rohit','rizwan']
k = i + j
print(k)

In [ ]:
i.append(j)
i

In [ ]:
i = ['Ayushi','ayush']
j = ['Rohit','rizwan']
i.extend(j)
i

In [ ]:
input = [23,54,74,True,["Ruby",False,'Python'],0,1,None,23]
output = [23,54,74,True,"Ruby",False,'Python',0,1,None,23]

In [ ]:
x = int(input())
y = int(input())
print(x,y)
if x > y:
    print('x is great',x)
else:
    print("y is great",y)

In [ ]:
v = ['bottle','mice','pen']
print(v)

In [ ]:
v[2] = 'Duster'
v

In [ ]:
v[:2] = ['book','writingpad']
v

In [ ]:
# insert 
v

In [ ]:
v.insert(2,"Eraser")
v

In [ ]:
v.insert(0,"Sharpner")
v

In [ ]:
v.index("book")

In [ ]:
b = ['Sharpner', 'book', 'writingpad', 'Eraser','writingpad', 'Duster','book']
print(b.index('book',2))
print(b.index('writingpad',3 ))

In [ ]:
list1 = ['Sharpner', 'book', 'writingpad', 'Eraser','writingpad', 'Duster','book']
new_list = []
count = 0
for i in list1:
    if i.lower() == 'book':
        new_list.append(count)
    count += 1
print(new_list)

In [ ]:
list1 = ['Sharpner', 'book', 'writingpad', 'Eraser','writingpad', 'Duster','book']
list1.pop()
print(list1)

In [ ]:
list1.pop()
print(list1)

In [ ]:
list1.pop(2)
print(list1)

In [ ]:
list1.remove('book')
print(list1)

In [ ]:
list1.clear()
print(list1)

In [ ]:
list1.append("printer")
print(list1)

In [ ]:
del list1

In [ ]:
list1

In [ ]:
list2 = ['watch', 'mouse','pen','bottle']
print(list2)
list2.sort()
print(list2)

In [ ]:
list3 = [345,235,543,64,45,765]
list3.sort()
print(list3)

In [ ]:
list3 = [345,235,543,64,45,765]
list3.sort(reverse=True)
print(list3)

In [ ]:
list3.reverse()
print(list3)

In [ ]:
list3 = [345,235,543,64,45,765]
copy_lst = list3.copy() # return shallow copy of the list
print(list3)
print(copy_lst)

In [ ]:
copy_lst[0] = 500
print(copy_lst)
print(list3)

In [ ]:
import numpy as np
arr = np.array([500, 235, 543, 64, 45, 765])
v_arr = arr.view()
print("orignal",arr)
print("View",v_arr)              

orignal [500 235 543  64  45 765]
View [500 235 543  64  45 765]


In [45]:
arr[0] = 900
print(arr)
print(v_arr)

[900 235 543  64  45 765]
[900 235 543  64  45 765]


In [ ]:
v_arr[3] = 5783
print(v_arr)
print(arr)

[ 900  235  543 5783   45  765]
[ 900  235  543 5783   45  765]


In [ ]:
help(list.copy)

In [ ]:
list3.append("Laptop")
print(list3)
print(copy_lst)

In [ ]:
copy_lst.append('CPU')
print(list3)
print(copy_lst)

In [2]:
# Count
x = [900,  235,  543, 45, 5783,  45, 765]
x.count(543)

1