In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [5]:
x = [2,5,7,6]
arr1 = np.array([2,5,7,6])
print(arr1)
print(type(arr1))
print(type(x))

[2 5 7 6]
<class 'numpy.ndarray'>
<class 'list'>


In [7]:
arr1 = np.array([2,5,7,6])
print(arr1.ndim)
print(arr1.dtype)

1
int32


In [11]:
arr1 = np.array([2,5.3,7,6])
print(arr1)
print(arr1.ndim)
print(arr1.dtype)

[2.  5.3 7.  6. ]
1
float64


In [9]:
arr1 = np.array([2,5,'7',6])
print(arr1.ndim)
print(arr1.dtype)

1
<U11


In [10]:
arr1 = np.array(["x",'y','z'])
print(arr1.ndim)
print(arr1.dtype)

1
<U1


In [15]:
arr2d = np.array([[2,4,6]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)

[[2 4 6]]
2
(1, 3)
3


In [16]:
arr2d = np.array([[2,4,6],[2,3,5]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)

[[2 4 6]
 [2 3 5]]
2
(2, 3)
6


In [19]:
arr2d = np.array([[2,4,6],[2,3,5],[6,7,9]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)

[[2 4 6]
 [2 3 5]
 [6 7 9]]
2
(3, 3)
9


In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6]]])
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)


[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)


In [23]:
arr3d = np.array([[[1,2,3],[4,5,6]],
                  [[1,5,3],[64,5,46]]])
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  5  3]
  [64  5 46]]]
3
(2, 2, 3)


In [24]:
arr3d = np.array([[[1,2,3],[4,5,6],[11,22,33]],
                  [[1,5,3],[643,63,45],[64,5,46]]])
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

[[[  1   2   3]
  [  4   5   6]
  [ 11  22  33]]

 [[  1   5   3]
  [643  63  45]
  [ 64   5  46]]]
3
(2, 3, 3)


In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6],[11,22,33]],
                  [[1,5,3],[643,63,45],[64,5,46]]],
                  ndmin=10)
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

[[[[[[[[[[  1   2   3]
         [  4   5   6]
         [ 11  22  33]]

        [[  1   5   3]
         [643  63  45]
         [ 64   5  46]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 2, 3, 3)


In [26]:
arr3d = np.array([[[1,2,3],[4,5,6],[11,22,33]],
                  [[1,5,3],[643,63,45],[64,5,46]]],
                  dtype=float)
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

[[[  1.   2.   3.]
  [  4.   5.   6.]
  [ 11.  22.  33.]]

 [[  1.   5.   3.]
  [643.  63.  45.]
  [ 64.   5.  46.]]]
3
(2, 3, 3)


In [28]:
arr3d = np.array([[[1,2,3],[4,5,6],[11,22,33]],
                  [[1,5,3],[643,63,45],[64,5,46]]],
                  dtype=object)
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.dtype)

[[[1 2 3]
  [4 5 6]
  [11 22 33]]

 [[1 5 3]
  [643 63 45]
  [64 5 46]]]
3
(2, 3, 3)
object


In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((5,3),dtype=int,)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
x = np.arange(10)
print(x)
print(type(x))
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [33]:
x = np.arange(2,10)
print(x)
print(type(x))
print(x.shape)

[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(8,)


In [35]:
x = np.arange(2,10,2)
print(x)
print(type(x))
print(x.shape)
print(x.dtype)

[2 4 6 8]
<class 'numpy.ndarray'>
(4,)
int32


In [36]:
x = np.arange(2,10,2,dtype=float)
print(x)
print(type(x))
print(x.shape)
print(x.dtype)

[2. 4. 6. 8.]
<class 'numpy.ndarray'>
(4,)
float64


In [38]:
y = np.linspace(3,10)
print(y)
print(y.size)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]
50


In [39]:
y = np.linspace(3,10,num = 15)
print(y)
print(y.size)

[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5
 10. ]
15


In [41]:
y = np.linspace(3,4,num = 15)
print(y)
print(y.size)
print(y.ndim)

[3.         3.07142857 3.14285714 3.21428571 3.28571429 3.35714286
 3.42857143 3.5        3.57142857 3.64285714 3.71428571 3.78571429
 3.85714286 3.92857143 4.        ]
15
1


In [45]:
z = np.logspace(3,50)
print(z)

[1.00000000e+03 9.10298178e+03 8.28642773e+04 7.54312006e+05
 6.86648845e+06 6.25055193e+07 5.68986603e+08 5.17947468e+09
 4.71486636e+10 4.29193426e+11 3.90693994e+12 3.55648031e+13
 3.23745754e+14 2.94705170e+15 2.68269580e+16 2.44205309e+17
 2.22299648e+18 2.02358965e+19 1.84206997e+20 1.67683294e+21
 1.52641797e+22 1.38949549e+23 1.26485522e+24 1.15139540e+25
 1.04811313e+26 9.54095476e+26 8.68511374e+27 7.90604321e+28
 7.19685673e+29 6.55128557e+30 5.96362332e+31 5.42867544e+32
 4.94171336e+33 4.49843267e+34 4.09491506e+35 3.72759372e+36
 3.39322177e+37 3.08884360e+38 2.81176870e+39 2.55954792e+40
 2.32995181e+41 2.12095089e+42 1.93069773e+43 1.75751062e+44
 1.59985872e+45 1.45634848e+46 1.32571137e+47 1.20679264e+48
 1.09854114e+49 1.00000000e+50]


In [48]:
np.log10(2)

0.3010299956639812

In [51]:
x = np.arange(12,18)
print(x)
reshape_x = x.reshape((2,3))
print(reshape_x)

[12 13 14 15 16 17]
[[12 13 14]
 [15 16 17]]


In [53]:
x = np.arange(12,18)
print(x)
print(x.ndim)
reshape_x = x.reshape((3,2))
print(reshape_x)
print(reshape_x.ndim)

[12 13 14 15 16 17]
1
[[12 13]
 [14 15]
 [16 17]]
2


In [54]:
x = np.arange(12,18)
print(x)
print(x.ndim)
reshape_x = x.reshape((1,3,2))
print(reshape_x)
print(reshape_x.ndim)

[12 13 14 15 16 17]
1
[[[12 13]
  [14 15]
  [16 17]]]
3


In [57]:
a = np.array([11,22,33])
b = np.array([1,32,43])
print(a + b)
print(np.add(a,b))

[12 54 76]
[12 54 76]


In [58]:
a = np.array([11,22,33])
b = np.array([1,32,43])
print(a - b)
print(np.subtract(a,b))

[ 10 -10 -10]
[ 10 -10 -10]


In [61]:
a = np.array([11,22,33])
b = np.array([1,32,43])
print(a * b)
print(np.multiply(a,b))
print(np.matmul(a,b))

[  11  704 1419]
[  11  704 1419]
2134


In [63]:
a = np.array([11,22,33])
b = np.array([1,32,43])
print(a / b)
print(np.divide(a,b))

[11.          0.6875      0.76744186]
[11.          0.6875      0.76744186]


In [ ]:
pip install scipy

In [71]:
from scipy import stats

In [ ]:
x = np.array([3,5,53,34,5,7,5,34,5,7,5,34,5,7,6])
print(x.min())
print(x.max())
print(x.mean())
print(np.median(x))
print(stats.mode(x))
print(x.std())
print(x.var())

3
53
14.333333333333334
6.0
ModeResult(mode=5, count=6)
15.35650423183031
235.82222222222222


In [78]:
x = np.array([3,5,53,34,5,7,5,34,5,7,5,34,5,7,6])
print(x[5])
print(x[3:])

7
[34  5  7  5 34  5  7  5 34  5  7  6]


In [85]:
u = np.array([[3,5,2,5],[7,45,6,6]])
print(u)
print(u[0])
print(u[1])
print(u[0][2])
print(u[1][-1])
print(u[0][1:])

[[ 3  5  2  5]
 [ 7 45  6  6]]
[3 5 2 5]
[ 7 45  6  6]
2
6
[5 2 5]


In [87]:
u = np.array([[3,5,2,5],[7,45,6,6]])
print(u)
u[0][1] = 10
print(u)

[[ 3  5  2  5]
 [ 7 45  6  6]]
[[ 3 10  2  5]
 [ 7 45  6  6]]


In [89]:
u = np.array([[3,5,2,5],[7,45,6,6]])
print(u)
u[0][1:] = [7,8,9]
print(u)

[[ 3  5  2  5]
 [ 7 45  6  6]]
[[ 3  7  8  9]
 [ 7 45  6  6]]


In [91]:
u = np.array([[3,5,2,5],[7,45,6,6]])
v = np.array([[4,5,6,3],[7,8,34,7]])
print(u[0] + v[0])
print(u[0] + v[1])

[ 7 10  8  8]
[10 13 36 12]


In [ ]:
u = np.array([[3,5,2,5],[7,45,6,6]])
v = np.array([[4,5,6,3],[7,8,34,7]])
print(u[0] + v[0])
print(u[1] + v[1])

In [ ]:
u = np.array([[3,5,2,5],[7,45,6,6]])
v = np.array([[4,5,6,3],[7,8,34,7]])
concat = np.concatenate((u,v))
print(concat)

[[ 3  5  2  5]
 [ 7 45  6  6]
 [ 4  5  6  3]
 [ 7  8 34  7]]


In [94]:
u = np.array([[3,5,2,5],[7,45,6,6]])
v = np.array([[4,5,6,3],[7,8,34,7]])
concat = np.concatenate((u,v),axis=0)
print(concat)

[[ 3  5  2  5]
 [ 7 45  6  6]
 [ 4  5  6  3]
 [ 7  8 34  7]]


In [95]:
u = np.array([[3,5,2,5],[7,45,6,6]])
v = np.array([[4,5,6,3],[7,8,34,7]])
concat = np.concatenate((u,v),axis=1)
print(concat)

[[ 3  5  2  5  4  5  6  3]
 [ 7 45  6  6  7  8 34  7]]


In [96]:
op = np.array([[ 3, 5,  2,  5,  4 , 5,  6,  3], [ 7, 45,  6,  6,  7,  8, 34,  7]])
print(op)

[[ 3  5  2  5  4  5  6  3]
 [ 7 45  6  6  7  8 34  7]]


In [97]:
trans_op = op.T 
print(trans_op)

[[ 3  7]
 [ 5 45]
 [ 2  6]
 [ 5  6]
 [ 4  7]
 [ 5  8]
 [ 6 34]
 [ 3  7]]


In [98]:
op = np.array([[ 3, 5,  2,  5,  4 , 5,  6,  3]])
op_sort = np.sort(op)
print(op_sort)

[[2 3 3 4 5 5 5 6]]


In [ ]:
op = np.array([[ 3, 5,  2,  5,],[  4 , 5,  6,  3]])
op_sort = np.sort(op,)
print(op_sort)

[[2 3 5 5]
 [3 4 5 6]]


In [103]:
op = np.array([[ 3, 5,  7,  5,],[  2 , 5,  6,  3]])
op_sort = np.sort(op,axis = 0)
print(op_sort)

[[2 5 6 3]
 [3 5 7 5]]


In [104]:
op = np.array([[ 3, 5,  7,  5,],[  2 , 5,  6,  3]])
op_sort = np.sort(op,axis = 1)
print(op_sort)

[[3 5 5 7]
 [2 3 5 6]]


In [106]:
op = np.array([ 3, 5,  7,  5,])
copy_op = op.copy()
print(copy_op)
view_op  = op.view()
print(view_op)

[3 5 7 5]
[3 5 7 5]


In [107]:
op[1] = 10
print(op)
print(copy_op)
print(view_op)

[ 3 10  7  5]
[3 5 7 5]
[ 3 10  7  5]


In [108]:
view_op[-1] = 100
print(op)
print(copy_op)
print(view_op)

[  3  10   7 100]
[3 5 7 5]
[  3  10   7 100]
